aoi_center_coords: 47.42103595201548, 10.985322244838923
aoi_crs_epsg: ''
aoi_dimension1_mm: 100
aoi_dimension2_mm: 100
aoi_name: Zugspitze
aoi_shape_type: hexagon
generate_aoi: true
generate_map: true
input_file: ''
input_folder: ''
map_attempt_label_repositioning: true
map_city: true
map_dpi: 300
map_filename: Zugspitze.png
map_font_family: Arial
map_font_size: 7
map_fontweight: bold
map_footway: true
map_hamlet: false
map_isolated_dwelling: false
map_keep_markers: true
map_light_rail: true
map_logo: false
map_logo_height_cm: 0.5
map_logo_width_cm: 3.8
map_motorway: true
map_mountain_hut_color: black
map_mountain_hut_fontweight: medium
map_mountain_hut_label_italic: false
map_mountain_huts: true
map_narrow_gauge: true
map_neighbourhood: false
map_path: true
map_peak_color: black
map_peak_fontweight: bold
map_peak_label_italic: false
map_peak_label_padding_cm: 0.0
map_peaks: true
map_primary: true
map_rail: true
map_railways: true
map_residential: true
map_secondary: true
map_service: true
map_settlement_color: black
map_settlement_fontweight: medium
map_settlement_label_italic: false
map_settlement_label_padding_cm: 0.1
map_settlements: true
map_streets: true
map_suburb: true
map_tertiary: true
map_town: true
map_track: true
map_trunk: true
map_village: true
map_water: true
map_water_canal: true
map_water_color: '0.5'
map_water_lake: true
map_water_lock: true
map_water_reservoir: true
map_water_river: true
map_waterway_canal: true
map_waterway_color: '0.5'
map_waterway_ditch: false
map_waterway_drain: false
map_waterway_river: true
map_waterway_stream: false
map_waterways: true
map_x_inverted: false
output_folder: outputs/Bergmodelle
prefer_etrs89_in_europe: true
save_generated_shapefile: false
save_geojson: true
scale: 100000
use_bulk: false
